### ISSUE TITLE
warning in Home Assistant

### ISSUE THREAD

**Issue by ElBielas** [max13fr/AirzoneCloudDaikin#4]
Hi Max, could you fix this warning ? Thanks

Logger: homeassistant.loader
Source: loader.py:802 
First occurred: 22:52:17 (1 occurrences) 
Last logged: 22:52:17

No 'version' key in the manifest file for custom integration 'airzoneclouddaikin'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'airzoneclouddaikin'

**Comment by max13fr** [comment]
Hi,

Just fixed in the correct repo (https://github.com/max13fr/AirzonecloudDaikin-HomeAssistant), you can replace your custom_components/airzoneclouddaikin

Max
